accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from accounts.views import (
    signup,
)

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name="login.html"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout.html"),
    path("signup/", signup, name="signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("receipts/", include("receipts.urls")),
    path("", RedirectView.as_view(url=reverse_lazy("home"))),
]

receipts/urls.py
from django.urls import path

from receipts.views import (
    ReceiptListView,
    ExpenseCategoryListView,
    AccountListView,
    ExpenseCategoryCreateView,
    AccountCreateView,
    ReceiptCreateView,
)

urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
    path("categories/", ExpenseCategoryListView.as_view(), name="list_categories"),
    path("accounts/", AccountListView.as_view(), name="list_accounts"),
    path("categories/create/", ExpenseCategoryCreateView.as_view(), name="create_category"),
    path("accounts/create/", AccountCreateView.as_view(), name="create_account"),
    path("create/", ReceiptCreateView.as_view(), name="create_receipt"),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL
# Create your models here.


class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="categories",
        on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="accounts",
        on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(max_digits=10, decimal_places=3)
    tax = models.DecimalField(max_digits=10, decimal_places=3)
    date = models.DateField()
    purchaser = models.ForeignKey(
        USER_MODEL,
        related_name="receipts",
        on_delete=models.CASCADE
    )
    category = models.ForeignKey(
        "ExpenseCategory",
        related_name="receipts",
        on_delete=models.CASCADE
    )
    account = models.ForeignKey(
        "Account",
        null=True,
        related_name="receipts",
        on_delete=models.CASCADE
    )

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login
from django.shortcuts import redirect
# Create your views here.


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid:
            username = request.POST["username"]
            password = request.POST["password1"]
            user = User.objects.create_user(username, password)
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm(request.POST)
        context = {"form": form}
    return render(request, "registration/signup.html", context)

receipts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from django.shortcuts import redirect
from receipts.models import ExpenseCategory, Receipt, Account
# Create your views here.


class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = "receipts/list.html"

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)


class ExpenseCategoryListView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = "categories/list.html"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)


class AccountListView(LoginRequiredMixin, ListView):
    model = Account
    template_name = "accounts/list.html"

    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)


class ExpenseCategoryCreateView(CreateView):
    model = ExpenseCategory
    template_name = "categories/create.html"
    fields = ["name"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("list_categories")


class AccountCreateView(CreateView):
    model = Account
    template_name = "accounts/create.html"
    fields = ["name", "number"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("list_accounts")


class ReceiptCreateView(CreateView):
    model = Receipt
    template_name = "receipts/create.html"
    fields = ["vendor", "total", "tax", "date", "category", "account"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.purchaser = self.request.user
        item.save()
        return redirect("home")

accounts/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/app.css' %}">
  <title>Me Receipts</title>
</head>
<body>
  <header>
    <nav>
      <ul class="navigation">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'home' %}">Receipts</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'create_receipt' %}">Create receipt</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'list_accounts' %}">Accounts</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'create_account' %}">Create account</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'list_categories' %}">Categories</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'create_category' %}">Create category</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'logout.html' %}">Logout</a>
          </li>
      {% else %}
        <li class="nav-item">
            <a href="{% url 'signup' %}">Sign Up</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'login.html' %}">Login</a>
          </li>
      {% endif %}
      </ul>
    </nav>
  </header>
  <main>
    {% block content %}
    {% endblock content %}
  </main>
</body>
</html>

receipts/templates/accounts/create.html
{% extends 'base.html' %}

{% block content %}
  <div class="narrow-form">
    <h1>Create Account</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button>Create</button>
    </form>
  </div>
{% endblock content %}


{% load static %}

receipts/templates/accounts/list.html
{% extends 'base.html' %}

{%block content%}

<table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Number</th>
        <th>Number of receipts</th>
      </tr>
    </thead>
    <tbody>
      {% for account in account_list %}
      <tr>
        <td>{{account.name}}</td>
        <td>{{account.number}}</td>
        <td>{{account.receipts.all|length}}</td>
      </tr>
      {% endfor %}
    </tbody>
</table>
      
{% endblock content %}

receipts/templates/categories/create.html
{% extends 'base.html' %}

{% block content %}
  <div class="narrow-form">
    <h1>Create Category</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button>Create</button>
    </form>
  </div>
{% endblock content %}


{% load static %}

receipts/templates/categories/list.html
{% extends 'base.html' %}

{%block content%}

<table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Number of receipts</th>
      </tr>
    </thead>
    <tbody>
      {% for category in expensecategory_list %}
        <tr>
          <td>{{category.name}}</td>
          <td>{{category.receipts.all|length}}</td>
        </tr>
      {% endfor %}
    </tbody>
</table>

{% endblock content %}

receipts/templates/receipts/create.html
{% extends 'base.html' %}

{% block content %}
  <div class="narrow-form">
    <h1>Create Receipt</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button>Create</button>
    </form>
  </div>
{% endblock content %}


{% load static %}

receipts/templates/receipts/list.html
{% extends 'base.html' %}

{%block content%}
    <h1>Receipts</h1>
    <table>
        <thead>
        <tr>
            <th>Vendor</th>
            <th>Total</th>
            <th>Tax</th>
            <th>Date</th>
            <th>Category</th>
            <th>Account</th>
        </tr>
        </thead>
    <tbody>
        {% for receipt in receipt_list %}
            <tr>
                <td>{{receipt.vendor}}</td>
                <td>{{receipt.Total}}</td>
                <td>{{receipt.Tax}}</td>
                <td>{{receipt.Date}}</td>
                <td>{{receipt.category.name}}</td>
                <td>{{receipt.account.name}}</td>
            </tr>
        {% endfor %}
    </tbody>
    </table>
{% endblock content %}